development:
  user: fedoraAdmin
  password: fedorasea3admin_password
  url: http://hydrastg.library.cornell.edu/fedora
test: &TEST  
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/fedora-test" %>
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://your.production.server:8080/fedora
cucumber:
  <<: *TEST
